#!/usr/bin/env python3.5

import parser
import sys
import getopt
from util import msg
from util import Enum

import swift
import java
import php
import javascript
import jsongen

import server

SourceTarget = Enum(["SWIFT", "JAVA", "PHP", "JS", "JSON"])

VERSION_MAJOR=3
VERSION_MINOR=7
VERSION = str(VERSION_MAJOR) + "." + str(VERSION_MINOR)



def usage():                         
    msg("\nUsage:\tjidou --help | --validate [AAAFILE] | --LANGUAGE [AAAFILE] [OUTPUT] | --server [AAAFILE]")
    msg("\n\tDefault aaa input filename:\tmobile.aaa")
    msg("\tDefault src output filename:\t<stdout>")
    msg("\n\tUse --validate to check the AAA file for syntax errors")
    msg("\n\tThe --LANG flag supports the following language flags:")
    msg("\t\tSwift\tlanguage with:\t-s, --swift")
    msg("\t\tJava\tlanguage with:\t-j, --java")
    msg("\t\tJSON\tlanguage with:\t-X, --json")
    msg("\t\tPHP\tlanguage with:\t-p, --php")
    msg("\t\tJavaScript\tlanguage with:\t-J, --javascript")
    msg("\n\tUse -S, --server to run a small test server on port 4444")

def main(argv):                         
    try:
        opts, args = getopt.getopt(argv, "sjphvJXS", ["swift", "java", "php", "help", "validate", "javascript", "json", "server"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    source_target = None 
    validation_only = False
    run_server = False

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        elif opt in ("-S", "--server"):
            run_server = True
        elif opt in ("-s", "--swift"):
            source_target=SourceTarget.SWIFT
        elif opt in ("-j", "--java"):
            source_target=SourceTarget.JAVA
        elif opt in ("-p", "--php"):
            source_target=SourceTarget.PHP
        elif opt in ("-J", "--javascript"):
            source_target=SourceTarget.JS
        elif opt in ("-X", "--json"):
            source_target=SourceTarget.JSON
        elif opt in ("-v", "--validate"):
            validation_only = True

    if not source_target and not validation_only and not run_server:
        usage()
        sys.exit(2)

    input_filename = args[0] if len(args) >= 1 else "mobile.aaa"
    output_filename = args[1] if len(args) >= 2 else "<STDOUT>"

    if validation_only:
        msg("Parsing...")
        parser.parse(input_filename, VERSION_MAJOR, VERSION_MINOR)
        msg("Looks wunderful :)")
        sys.exit(0)


    if not run_server:
        msg("Generate source code in: " + source_target)
        msg("Input  file: " + input_filename )
        msg("Output file: " + output_filename + "\n\n")

    token_tree = parser.parse(input_filename, VERSION_MAJOR, VERSION_MINOR)

    if run_server:
        server.run(4444, token_tree)
        sys.exit(0)
    elif source_target == SourceTarget.SWIFT:
        source = swift.generate(token_tree)
    elif source_target == SourceTarget.JSON:
        source = jsongen.generate(token_tree)
    elif source_target == SourceTarget.JAVA:
        source = java.generate(token_tree)
    elif source_target == SourceTarget.PHP:
        source = php.generate(token_tree)
    # elif source_target == SourceTarget.JS
        # source = javascript.generate(token_tree)

    if output_filename == "<STDOUT>":
        print(source)
    else:
        with open(output_filename, 'w') as out:
            out.write(source + '\n')


if __name__ == "__main__":
    msg("Automatic API interface class generator. (Version: " + VERSION + ")")
    main(sys.argv[1:])
