#!/usr/bin/env python3.5

import parser
import sys
import getopt
from util import msg
from util import Enum

import swift
import java
import php
import javascript
import jsongen

SourceTarget = Enum(["SWIFT", "JAVA", "PHP", "JS", "JSON"])

VERSION_MAJOR=3
VERSION_MINOR=6
VERSION = str(VERSION_MAJOR) + "." + str(VERSION_MINOR)



def usage():                         
    msg("Usage:\n\tparser.py [--validate] | [--help] [--swift | --java | --php | --javascript | --json] [input] [output]")
    msg("\n\tOne and only one source format has to be defined.")
    msg("\n\tUse --validate to check the AAA file for syntax errors")
    msg("\tDefault input  filename: mobile.aaa")
    msg("\tDefault output filename: <stdout>")

def main(argv):                         
    try:
        opts, args = getopt.getopt(argv, "sjphvJX", ["swift", "java", "php", "help", "validate", "javascript", "json"])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    source_target = None 
    validation_only = False

    for opt, arg in opts:
        if opt in ("-h", "--help"):
            usage()
            sys.exit()
        elif opt in ("-s", "--swift"):
            source_target=SourceTarget.SWIFT
        elif opt in ("-j", "--java"):
            source_target=SourceTarget.JAVA
        elif opt in ("-p", "--php"):
            source_target=SourceTarget.PHP
        elif opt in ("-J", "--javascript"):
            source_target=SourceTarget.JS
        elif opt in ("-X", "--json"):
            source_target=SourceTarget.JSON
        elif opt in ("-v", "--validate"):
            validation_only = True

    if not source_target and not validation_only:
        usage()
        sys.exit(2)

    input_filename = args[0] if len(args) >= 1 else "mobile.aaa"
    output_filename = args[1] if len(args) >= 2 else "<STDOUT>"

    if validation_only:
        msg("Parsing...")
        parser.parse(input_filename, VERSION_MAJOR, VERSION_MINOR)
        msg("Looks wunderful :)")
        sys.exit(0)


    msg("Generate source code in: " + source_target)
    msg("Input  file: " + input_filename )
    msg("Output file: " + output_filename + "\n\n")

    token_tree = parser.parse(input_filename, VERSION_MAJOR, VERSION_MINOR)

    if source_target == SourceTarget.SWIFT:
        source = swift.generate(token_tree)
    elif source_target == SourceTarget.JSON:
        source = jsongen.generate(token_tree)
    elif source_target == SourceTarget.JAVA:
        source = java.generate(token_tree)
    elif source_target == SourceTarget.PHP:
        source = php.generate(token_tree)
    # elif source_target == SourceTarget.JS
        # source = javascript.generate(token_tree)

    if output_filename == "<STDOUT>":
        print(source)
    else:
        with open(output_filename, 'w') as out:
            out.write(source + '\n')


if __name__ == "__main__":
    msg("Automatic API interface class generator. (Version: " + VERSION + ")")
    main(sys.argv[1:])
